#! /bin/sh

# Test update-binfmts --find.

: ${srcdir=.}
. "$srcdir/testlib.sh"

init
fake_proc

expect_pass 'magic: install' \
	    'update_binfmts_proc --install test /bin/sh --magic ABCD'
echo 'ABCD' >"$tmpdir/program.ext"
chmod +x "$tmpdir/program.ext"
echo /bin/sh >"$tmpdir/1.exp"
expect_pass 'magic: run find' \
	    'update_binfmts_proc --find "$tmpdir/program.ext" >"$tmpdir/1.out"'
expect_pass 'magic: find result OK' \
	    'diff -u "$tmpdir/1.out" "$tmpdir/1.exp"'

expect_pass 'magic: disable' \
	    'update_binfmts_proc --disable test'
touch "$tmpdir/2.exp"
expect_pass 'magic: run find (disabled)' \
	    'update_binfmts_proc --find "$tmpdir/program.ext" >"$tmpdir/2.out"'
expect_pass 'magic: find result OK' \
	    'diff -u "$tmpdir/2.out" "$tmpdir/2.exp"'

finish
